### ISSUE TITLE
Ubuntu problem: AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by yfukai** [macronucleus/chromagnon#25]
After updating to v0.87, the program stopped working in Ubuntu with the error `AttributeError: module 'time' has no attribute 'clock'`, while it works in macOS. I suppose this is a Python version problem while packaging. 
The following is my system information:

```bash
cat /etc/lsb-release 
#DISTRIB_ID=Ubuntu
#DISTRIB_RELEASE=18.04
#DISTRIB_CODENAME=bionic
#DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

```python
In [1]: from __future__ import print_function 
   ...: import sys; print(sys.version) 
   ...: import platform; print(platform.platform()) 
   ...: import skimage; print("scikit-image version: {}".format(skimage.__versio
   ...: n__)) 
   ...: import numpy; print("numpy version: {}".format(numpy.__version__)) 
```

```
3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
Linux-4.15.0-135-generic-x86_64-with-debian-buster-sid
scikit-image version: 0.19.0.dev0
numpy version: 1.16.6
```
Thanks!

**Comment by macronucleus** [comment]
Thank you for reporting this critical problem! (Yes, I changed python version!)
I fixed it, please try the new version v0.88 (binary is only for ubuntu).
I believe it is a simple problem, so I close this thread immediately.
If there are additional problems, please feel free to reopen.
